---
- name: Run pre tasks
  include: pre.yml

# - name: create user
#   include: user.yml

- name: install bpf compile packages
  include: bpf.yml

- name: install libbpf and bpf headers
  include: libbpf.yml

- name: install bpf dev tools
  include: tools.yml

- name: install tpstat
  include: tpstat.yml