version: '3.8'
services:
    oai-upf:
        container_name: "oai-upf"
        image: oaisoftwarealliance/oai-upf:v2.0.1
        expose:
            - 2152/udp
            - 8805/udp
            - 8080/tcp
        volumes:
            - ./conf/basic_nrf_config_ebpf.yaml:/openair-upf/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        # depends_on:
        #     - oai-nrf
        #     - oai-smf
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        network_mode: host
        extra_hosts:
            - "oai-ext-dn:192.168.72.135"
        #     - "oai-nrf:192.168.70.130"
    oai-ext-dn:
        privileged: true
        init: true
        container_name: oai-ext-dn
        image: oaisoftwarealliance/trf-gen-cn5g:latest
        environment:
            - EBPF_GW_SETUP=yes
            - EBPF_GW_N6_IP_ADDR=192.168.72.135
            - GW_SGI_IP_ADDR=192.168.70.135
            - GW_N3_IP_ADDR=192.168.71.135
            - UE_IP_ADDRESS_POOL=12.1.1.0/24
            - N6_UPF_IP_ADDR=192.168.72.129
            - SGI_DEMO_OAI_ADDR=192.168.70.129
        healthcheck:
            test: /bin/bash -c "ip r | grep 12.1.1"
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            public_net:
                ipv4_address: 192.168.70.135
            n3_net:
                ipv4_address: 192.168.71.135
            n6_net:
                ipv4_address: 192.168.72.135
networks:
    public_net:
        driver: bridge
        name: demo-oai-public-net
        ipam:
            config:
                - subnet: 192.168.70.128/26
        driver_opts:
            com.docker.network.bridge.name: "demo-oai"
    n3_net:
        driver: bridge
        name: demo-oai-n3-net
        ipam:
            config:
                - subnet: 192.168.71.128/26
        driver_opts:
            com.docker.network.bridge.name: "demo-n3"
    n6_net:
        driver: bridge
        name: demo-oai-n6-net
        ipam:
            config:
                - subnet: 192.168.72.128/26
        driver_opts:
            com.docker.network.bridge.name: "demo-n6"
