- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true
  become: true

- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true
  become: true

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
  become: true

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true
  become: true

- name: Update apt and install Docker Compose CLI plugin
  apt:
    name: docker-compose-plugin
    state: latest
    update_cache: true
  become: true

- name: Install Docker Module for Python
  pip:
    name: docker

# sudo groupadd docker
- name: Create "docker" group (sudo groupadd docker)
  group:
    name: docker
    state: present
  become: true

# sudo usermod -aG docker root
- name: Add remote "ubuntu" user to "docker" group (sudo usermod -aG docker $USER)
  user:
    name: "{{ user }}"
    group: docker
    append: yes
  become: true

- name: Unconditionally reboot the machine with all defaults
  ansible.builtin.reboot:
  become: yes

- name: Log into DockerHub
  community.docker.docker_login:
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"