# ---- netsize ----
- name: Run a script for starting tracing (bpftrace)
  ansible.builtin.command: timeout {{ duration }} sh /home/{{ user }}/tpstat/network/net/netsize.bt
  register: netsize_command
  async: "{{ aduration }}"
  poll: 0
  become: yes
  ignore_errors: yes

- name: Check on an async task for traffic (iperf)
  async_status:
    jid: "{{ netsize_command.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 100
  delay: 10
  ignore_errors: yes

- name: Get results from tracing (bpftrace)
  ansible.builtin.shell: cat {{ netsize_command.results_file }}
  register: netsize_command_results
  become: yes

# write to remote
- name: "Filter the tracing results we are interested in and save results them on remote machine"
  ansible.builtin.copy:
    content: "{{( netsize_command_results.stdout | from_json).stdout}}"
    dest: ~/netsize-{{ inventory_hostname }}

# copy remote copy to local machine
- name: "Save results from tracing on local machine"
  ansible.builtin.fetch:
    src: ~/netsize-{{ inventory_hostname }}
    dest: .results/netsize.out
    flat: yes
