- name: Run a script for starting tracing (bpftrace)
  ansible.builtin.command: timeout {{ duration }} bpftrace {{ tool }} > {{ tool }}.out
  args:
    chdir: "{{ dir }}"
  register: tool_command
  async: "{{ aduration }}"
  poll: 0
  become: yes
  ignore_errors: yes

- name: Check on an async task for {{ tool }} (bpftrace)
  async_status:
    jid: "{{ tool_command.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 100
  delay: 5
  become: yes
  ignore_errors: yes

- name: Get results from tracing (bpftrace)
  ansible.builtin.shell: cat {{ tool_command.results_file }}
  register: tool_command_results
  become: yes