
- name: Run a script using an executable in a system path
  ansible.builtin.command: 
    cmd: python3 tgn/stl_pcap_dns_push.py -t {{ time }} -f /tmp/rx_dns.pcap -s 10.0.2.4 -d 10.0.2.5 -r {{ kpps }}000
    chdir: /home/azureuser/trex-core/scripts
  # args:
  #   executable: python3
  environment:
    - PYTHONPATH: "/home/azureuser/trex-core/scripts/automation/trex_control_plane/interactive"
  when:
    - inventory_hostname in groups["az_trex"]
  register: trex_command
  async: "{{ aduration }}"
  poll: 0
  # become: yes
  ignore_errors: yes

- name: Sleep for 30 seconds (trex takes some time to read the pcap file) and continue with play
  wait_for:
    timeout: 30
  delegate_to: localhost

- name: Get results from tracing (bpftrace)
  ansible.builtin.shell: ./main.sh {{ tool }} {{ duration }} 1 {{ duration }} {{ kpps }}
  args:
    chdir: /home/azureuser/tools
    executable: /bin/bash
  become: yes
  when:
    - inventory_hostname in groups["az_sut"]

- name: Check on an async task for netsize (bpftrace)
  async_status:
    jid: "{{ trex_command.ansible_job_id }}"
  when:
    - inventory_hostname in groups["az_trex"]
  register: job_result
  until: job_result.finished
  retries: 100
  delay: 10
  # become: yes
  ignore_errors: yes

- name: Fetch stuff from the remote and save to local
  synchronize:  src=/home/azureuser/tools/results dest=.results/kpps={{ kpps }} mode=pull
  when:
    - inventory_hostname in groups["az_sut"]

- name: Delete content & directory
  file:
    state: absent
    path: /home/azureuser/tools/results/
  become: yes
  when:
    - inventory_hostname in groups["az_sut"]