- name: Creating a file with content
  copy:
    dest: "/home/open/pktgentrace.sh"
    content: |
      bpftrace tpstat/bpftrace/net/biodrop.bt
    mode: +x

- name: Creating a file with content
  copy:
    dest: "/home/open/pktgenmonitor.sh"
    content: |
      taskset -c $1 openssl speed -seconds $2 aes-256-cbc
    mode: +x

- name: Create script to start udp server
  copy:
    dest: "/home/open/pktgentraffic.sh"
    content: |
      /home/open/CppServer/bin/cppserver-performance-udp_echo_server
    mode: +x