
- name: Creating a file with content
  copy:
    dest: "/home/user/pktgentrace.sh"
    content: |
      bpftrace tpstat/bpftrace/net/biodrop.bt
    mode: +x

- name: Creating a file with content
  copy:
    dest: "/home/user/pktgenmonitor.sh"
    content: |
      taskset -c $1 openssl speed -seconds $2 aes-256-cbc
    mode: +x

- name: Create script to start udp server
  copy:
    dest: "/home/user/pktgen-dpdk/pktgentraffic.sh"
    content: |
      taskset -c 169 /home/user//CppServer/bin/cppserver-example-udp_echo_server 5678
    mode: +x