- name: Creating a file with content
  copy:
    dest: "/home/open/pktgentrace.sh"
    content: |
      echo 'Hello'
    mode: +x

- name: Creating a file with content
  copy:
    dest: "/home/open/pktgenmonitor.sh"
    content: |
      taskset -c $1 openssl speed -seconds $2 aes-256-cbc
    mode: +x

- name: Create script to start iperf
  copy:
    dest: "/home/open/pktgentraffic.sh"
    content: |
      cd /opt/pktgen-20.02.0 && ./app/x86_64-native-linuxapp-gcc/pktgen --vdev="net_vdev_netvsc0,iface=eth1" -- -T -P -m "2.[0]" -f /home/open/pktgen.lua
    mode: +x