---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/ubuntu:20.04
    pre_build_image: false
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  name: default
  test_sequence: 
    - destroy
    - create
    - converge
    # - idempotence
    - lint
    - verify