apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lVUTEwKzFod0pyMGxza2ZNZzZLVFlycHNObjdNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01NVEF1TVRVeUxqRTRNeTR4TUI0WERUSXlNRFV4TXpFNE16WXhNRm9YRFRNeQpNRFV4TURFNE16WXhNRm93RnpFVk1CTUdBMVVFQXd3TU1UQXVNVFV5TGpFNE15NHhNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFyRFFzWTd5dTBWdzVycUI2dWZtRVR4VTRFUGpQNXBZZ1lMaFMKeEcvNkRiaHYrSC8yR2NkZjRpamxsUXo2WDZRbi9lRjBPL1FNMnZaL2oxbithaTl2cXF0Kzh1aGxEYmNNcUtIUwowczk3eVRjbWcrR1RaZ1lGMmk3MDNwYU0yQzA1c1A4cXJ0THFrVlErUndYSGFIR1VCQmpGV3E0aFFtVk5LMTgxCkgyUmNDSGNzR0pOQ3daaC95QnhqKzgwVUdsM3g2RWt1MERVUE4rYVA3aWZ3TDRNcTlkaGNtNmU3QWIzelVhZUUKOS9SdlFobWZGeWtEZEhWT1p0ank1KytzSmRRNTJsWmtiZUFIQnFxOUNZUWVrMmlEcXRxaW1RS2F4OXI5TktuWQpIN0h6dXJKSmlkVmxld1M3eXZteEo1UTFpZFNKczNzMjBoVFJGQXYrRHBwQ0l2dWRWUUlEQVFBQm8xTXdVVEFkCkJnTlZIUTRFRmdRVW9WSGdBL1B0amhWWFB2aFJiNUZyOU0yNkFDd3dId1lEVlIwakJCZ3dGb0FVb1ZIZ0EvUHQKamhWWFB2aFJiNUZyOU0yNkFDd3dEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBUUVBb2N5eW5CME5zRGhUZkhycC9zSHhKNHZ0dDUvS2UyY1Y5cldxTEJMVkltcG1JVWl2VURCZ3ZYVTV4S1EzCmJPMzRqWmJqU2E0cE9hQVMrVFJTZ2luWENpNTlBVkFLK2V0aDZjL1hMQ1JhQU9KZnpTU2IzVjQ5QTdxS0F6R00KNkEwanlJUk1qYlRhaS9pNWd4aDNmR0RkNGhQNTJzV3prTWxLbHhDWmhJeFpIWWJsZTQ1RU5ZQVkra1B2L0FhVQp3RldyUkpzMWx4aHowNUFRdk9ndUdRbDZiaElpRVkyZW5LaXhud21TL2lySDNobWZmS3NBc2MyZW45bWVDYWcyCmwzRURJUmhvbDR3M2orNnlkREx3SkFUbm5qa2ZFWDYzNWVXRXY5U2Q5NFU2MTRDczBXL0plejRKMFBBRUtCdXoKZDVjNlNxMFhlcjRZU2ZIcGtITTZwU0lTM0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://192.168.122.182:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: WXd3K1l2d3ViUUt0b1hhZmZjYnA1RWtKRkRpWFJCNUZXQTAvR0hueHB3OD0K