---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-geerlingguy/docker-ubuntu2004-ansible:latest}
    # image: ubuntu:20.04
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    # pre_build_image: false
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  name: default
  test_sequence: 
    - destroy
    - create
    - converge
    # - idempotence # TODO: enable idempotence
    - lint
    - verify
