# publickey=$(cat ~/.ssh/id_rsa.pub) 
# ansible-playbook ansible/az_olan.yml -i ansible/inventory.ini --extra-vars "ssh_key_data='$publickey' olan_prefix=olanxxx"
# ansible-playbook ansible/plays/az_delete_olan.yml 

- name: Include task list in play
  import_playbook: plays/az_create_olan_loopback_testbed.yml

- name: Test Ping
  hosts:
    - az_trex
    - az_sut
  tasks:
  - action: ping

- hosts:
  - az_trex
  roles:
    - role: olan_azure_trex
      user: azureuser
      eth1: eth1
      eth2: eth2
      eth1_ip: "{{ hostvars['DUMMY_HOST']['trex_client48_nic_ip'] | default('10.0.2.4') }}"
      eth1_gw: "{{ hostvars['DUMMY_HOST']['sut_client48_nic_ip'] | default('10.0.2.5') }}"
      eth2_ip: "{{ hostvars['DUMMY_HOST']['trex_client16_nic_ip'] | default('10.0.3.4') }}"
      eth2_gw: "{{ hostvars['DUMMY_HOST']['sut_client16_nic_ip'] | default('10.0.3.5') }}"

  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: files/tgn
        dest: /home/azureuser/trex-core/scripts

# Call the NF and install it using the lifecycle events
- hosts:
  - az_sut
  tasks:

  - set_fact:
      events_type: "script"

  # - name: Test the lifecycle events play with script based VNF lifecycle bind9_vnf
  #   include: plays/events.yml
  #   vars:
  #     user: ubuntu
  #     vnf_repo: https://github.com/tariromukute/OOB-Server.git
  #     vnf_name: OOB-Server
  #     vnf_path: /home/azureuser/OOB-Server
  #     vnf_version: HEAD

- hosts:
  - az_sut
  roles:
    - role: olan_bpftrace
      user: azureuser

#Install ansible
- hosts:
  - az_sut
  tasks:
    - name: Install ansible python package
      pip:
        name: ansible

# - hosts:
#   - az_trex
#   tasks:
#     - name: Start the trex in the background
#       ansible.builtin.shell: sh t-rex-64 -i -c 2 -v 7 --no-ofed-check
#       become: yes
# - hosts:
#   - az_trex
#   tasks:
#     - name: Run a script using an executable in a system path
#       ansible.builtin.shell: 
#         cmd: python3 stl_dns_streams.py -t 10 -s 10.0.2.4 -d 10.0.2.5 -s 10.0.3.4 -d 10.0.3.5 -r 1
#         chdir: /home/azureuser/trex-core/scripts/tgn
#       args:
#         executable: python3
#       register: trex_command
#       async: 5
#       poll: 0
#       become: yes
#       ignore_errors: yes

#     - name: Check on an async task for netsize (bpftrace)
#       async_status:
#         jid: "{{ trex_command.ansible_job_id }}"
#       register: job_result
#       until: job_result.finished
#       retries: 100
#       delay: 10
#       become: yes
#       ignore_errors: yes

# - hosts:
#   - az_sut

#   vars:
#     tools:
#       - netcount.bt
#       - netsize.bt
#       - nettxlat-dev.bt
#       - runqlat.bt
#       - skblife.bt
#       - sockstat.bt
#       - skbdrop.bt --unsafe
#       # - syscount.bt
#     definitions_type: json
#     events_type: ansible

#   tasks:

#     - name: Include task list in play
#       include: plays/benchmark.yml
#       vars:
#         user: azureuser
#         duration: 62
#         aduration: 65
#         tool: "{{ item }}"
#         prefix: stl_imix_streams-rate_100-
#       loop: "{{ tools }}"
        