# - hosts: localhost
#   tasks:
#     - name: Test that my module works
#       vnfd_tosca:
#         vnfd: files/vnfd_import_multi_line.yml
#         target: aws
#       register: result

#     - debug: var=result

- name: Test Ping
  hosts:
    - client
    - server
  tasks:
  - action: ping