---
# tasks file for olan_open5gs
- name: Run pre tasks for Free5GC
  include: install.yml

- name: Install Free5GC
  include: configure.yml

- name: Configure Free5GC with UERANSIM VM
  include: webui.yml

- name: Run Free5GC
  include: run.yml